version: "3.5"
services:
  nethermind:
    build:
      context: nethermind
      args:
        UPSTREAM_VERSION: 1.29.1
        STAKER_SCRIPTS_VERSION: v0.1.0
        DATA_DIR: /data
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - data:/data
    environment:
      MODE: normal
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_SYNCCONFIG_SNAPSYNC: ""
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: 0.0.0.0
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_ENGINEHOST: 0.0.0.0
      NETHERMIND_JSONRPCCONFIG_ENGINEPORT: 8551
      NETHERMIND_HEALTHCHECKSCONFIG_UIENABLED: "true"
      EXTRA_OPTS: ""
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
volumes:
  data: {}
