version: "3.5"
services:
  nethermind:
    build:
      args:
        NETWORK: mainnet
        P2P_PORT: 30404
    ports:
      - 30404:30404/udp
      - 30404:30404/tcp
    image: nethermind.nethermind.public.dappnode.eth:1.0.51