version: "3.5"
services:
  nethermind:
    build:
      args:
        NETWORK: holesky
        P2P_PORT: 31804
    ports:
      - 31804:31804/udp
      - 31804:31804/tcp
    image: nethermind.nethermind.public.dappnode.eth:1.0.51